### ISSUE TITLE
Vehicles not displaying in character sheet.

### ISSUE THREAD

**Issue by c1t4rd** [OctarineSourcerer/cyberpunk2020#135]
I drag and drop the vehicle into the character sheet (since it's an item) and it doesn't display.

**Comment by OctarineSourcerer** [comment]
Hi! Sorry about the slow response - this should be fixed in 90cf0e6 :) As an added bonus, your items should now be sorted alphabetically too; they'd previously just been grouped into item types in the gear tab.

Let me know if that works for you!

**Comment by DrunXX** [comment]
vehicles still not shoiwng up character sheet

**Comment by OctarineSourcerer** [comment]
> vehicles still not shoiwng up character sheet

Hi! Are you using the git version? That seems to have it fixed still, just checked.

That being said, I should absolutely get those fixes and a couple others pushed out to regular Foundry-accessible release, I'll see if I can do that later today.

**Comment by DrunXX** [comment]
i just use the foundry version 
     
      
       
        Dnia 09 kwietnia 2024 11:40 Daniel Gomme ***@***.***&gt; napisał(a):
       
    
       
         
 
 vehicles still not shoiwng up character sheet 
 
 Hi! Are you using the git version? That seems to have it fixed still, just checked. 
 That being said, I should absolutely get those fixes and a couple others pushed out to regular Foundry-accessible release, I&#39;ll see if I can do that later today.

**Comment by OctarineSourcerer** [comment]
> i just use the foundry version Dnia 09 kwietnia 2024 11:40 Daniel Gomme ***@***.***&gt; napisał(a): vehicles still not shoiwng up character sheet Hi! Are you using the git version? That seems to have it fixed still, just checked. That being said, I should absolutely get those fixes and a couple others pushed out to regular Foundry-accessible release, I&#39;ll see if I can do that later today. — Reply to this email directly, github.com view it on GitHub , or github.com unsubscribe . You are receiving this because you commented. Message ID: &lt;OctarineSourcerer/cyberpunk2020/issues/135/2044686242 @ github . com&gt;

Gotcha! Okay, I've made the bugfixes available to FoundryVTT, update within and tell me how it goes
